# Generated by Django 3.2.6 on 2021-10-01 20:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('gere_coworking', '0001_manual_migration'),
    ]

    operations = [
        ### TABELA ADVERTÊNCIAS ###
        migrations.AddField(
            model_name='AdvertenciasModel',
            name='id_funcionario',
            field=models.ForeignKey(blank=False, db_column='id_funcionario', null=False,
                 on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.FuncionariosModel'),
        ),
        migrations.AddField(
            model_name='AdvertenciasModel',
            name='id_reserva',
            field=models.ForeignKey(blank=False, db_column='id_reserva', null=False,
                on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.ReservaModel')
        ),
        migrations.AlterModelTable(
            name='AdvertenciasModel',
            table='advertencias',
        ),
        
        ### TABELA CONVIDADOS ###
        migrations.AddField(
            model_name='ConvidadosModel',
            name='id_reserva',
            field=models.ForeignKey(blank=False, db_column='id_reserva', null=False,
                on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.ReservaModel')
        ),
        migrations.AddField(
            model_name='ConvidadosModel',
            name='id_cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True,
                on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.ClienteModel')
        ),
        migrations.AlterModelTable(
            name='ConvidadosModel',
            table='convidados',
        ),

        ### TABELA ESPACOS ###
        migrations.AddField(
            model_name='EspacosModel',
            name='id_tipo_espaco',
            field=models.ForeignKey(blank=False, db_column='id_tipo_espaco', null=False,
                on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.TipoespacoModel')
        ),
        migrations.AddField(
            model_name='EspacosModel',
            name='id_funcionario',
            field=models.ForeignKey(blank=True, db_column='ultima_alteracao', null=True,
                on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.FuncionariosModel')
        ),
        migrations.AlterModelTable(
            name='EspacosModel',
            table='espacos',
        ),

        ### TABELA EQUIPAMENTOS ###
        migrations.AddField(
            model_name='EquipamentosModel',
            name='id_funcionario',
            field=models.ForeignKey(blank=True, db_column='ultima_alteracao', null=True,
                on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.FuncionariosModel')
        ),
        migrations.AlterModelTable(
            name='EquipamentosModel',
            table='equipamentos',
        ),

        ### TABELA EQUIPAMENTORESERVA ###
        migrations.AddField(
            model_name='EquipamentoreservaModel',
            name='id_reserva',
            field=models.ForeignKey(blank=False, db_column='id_reserva', null=False,
                on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.ReservaModel')
        ),
        migrations.AddField(
            model_name='EquipamentoreservaModel',
            name='id_equipamento',
            field=models.ForeignKey(blank=False, db_column='id_equipamento', null=False,
                on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.EquipamentosModel')
        ),
        migrations.AddField(
            model_name='EquipamentoreservaModel',
            name='id_pagamento',
            field=models.ForeignKey(blank=True, db_column='id_pagamento', null=True,
                on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.PagamentoModel')
        ),
        migrations.AlterModelTable(
            name='EquipamentoreservaModel',
            table='equipamentoReserva',
        ),

        ### TABELA PACOTE HORAS ###
        migrations.AddField(
            model_name='PacotehorasModel',
            name='id_cliente',
            field=models.ForeignKey(blank=False, db_column='id_cliente', null=False,
                on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.ClienteModel')
        ),
        migrations.AddField(
            model_name='PacotehorasModel',
            name='id_cliente',
            field=models.ForeignKey(blank=True, db_column='id_empresa', null=True,
                on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.ClienteModel')
        ),
        migrations.AlterModelTable(
            name='PacotehorasModel',
            table='pacoteHoras',
        ),

        ### TABELA PAGAMENTO ###
        # migrations.AddField(
        #     model_name='PagamentoModel',
        #     name='id_reserva',
        #     field=models.ForeignKey(blank=True, db_column='id_reserva', null=True,
        #         on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.ReservaModel')
        # ),
        migrations.AddField(
            model_name='PagamentoModel',
            name='id_equipamento',
            field=models.ForeignKey(blank=True, db_column='id_equipamento', null=True,
                on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.EquipamentosModel')
        ),
        migrations.AlterModelTable(
            name='PagamentoModel',
            table='pagamento',
        ),

        ### TABELA RESERVA ###
        migrations.AddField(
            model_name='ReservaModel',
            name='id_cliente',
            field=models.ForeignKey(blank=False, db_column='id_cliente', null=False,
                on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.ClienteModel')
        ),
        migrations.AddField(
            model_name='ReservaModel',
            name='id_pagamento',
            field=models.ForeignKey(blank=True, db_column='id_pagamento', null=True,
                on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.PagamentoModel')
        ),
        migrations.AddField(
            model_name='ReservaModel',
            name='id_espaco',
            field=models.ForeignKey(blank=False, db_column='id_espaco', null=False,
                on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.EspacosModel')
        ),
        migrations.AddField(
            model_name='ReservaModel',
            name='id_pacote_horas',
            field=models.ForeignKey(blank=True, db_column='id_pacote_horas', null=True,
                on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.PacotehorasModel')
        ),
        migrations.AlterModelTable(
            name='ReservaModel',
            table='reserva',
        ),

        ### TABELA TIPO ESPACO ###
        migrations.AddField(
            model_name='TipoespacoModel',
            name='id_funcionario',
            field=models.ForeignKey(blank=True, db_column='ultima_alteracao', null=True,
                on_delete=django.db.models.deletion.DO_NOTHING, to='gere_coworking.FuncionariosModel')
        ),
        migrations.AlterModelTable(
            name='TipoespacoModel',
            table='tipoEspaco',
        ),
    ]
