# Generated by Django 3.2.6 on 2021-10-01 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0002_manual_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=128)),
                ('cnpj', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=12)),
                ('logradouro', models.CharField(max_length=45)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=35)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('database', models.CharField(max_length=128)),
                ('domain', models.ForeignKey(blank=True, db_column='domain', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='domains.domain')),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
    ]
