# Generated by Django 3.2.6 on 2021-10-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gere_coworking', '0002_manual_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertenciasmodel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clientemodel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='convidadosmodel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='equipamentoreservamodel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='equipamentosmodel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='espacosmodel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='funcionariosmodel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pacotehorasmodel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pagamentomodel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reservamodel',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipoespacomodel',
            options={'managed': False},
        ),
    ]
