# Generated by Django 3.2.6 on 2021-10-01 20:06

from django.db import migrations, models
from django.core.management import call_command
from django.conf import settings
from django.core.serializers import base, python
from django.db.migrations import operations

def load_fixture(apps, schema_editor):
    # Save the old _get_model() function
    old_get_model = python._get_model

    # Define new _get_model() function here, which utilizes the apps argument to
    # get the historical version of a model. This piece of code is directly stolen
    # from django.core.serializers.python._get_model, unchanged. However, here it
    # has a different context, specifically, the apps variable.
    def _get_model(model_identifier):
        try:
            return apps.get_model(model_identifier)
        except (LookupError, TypeError):
            raise base.DeserializationError("Invalid model identifier: '%s'" % model_identifier)

    # Replace the _get_model() function on the module, so loaddata can utilize it.
    python._get_model = _get_model

    try:
        # Call loaddata command
        call_command('loaddata', 'tests/fixures/domains.json')
    finally:
        # Restore old _get_model() function
        python._get_model = old_get_model

def get_operations():
    operations = [
        migrations.AddField(
            model_name='Domain',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='Domain',
            table='domain',
        ),
    ]
    if settings.AUTOMATIC_TEST:
        operations.append(migrations.RunPython(load_fixture))
    return operations

class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='Domain',
    #         name='isActive',
    #         field=models.BooleanField(default=False),
    #     ),
    #     migrations.AlterModelTable(
    #         name='Domain',
    #         table='domain',
    #     ),
    # ]
    operations = get_operations()








